version: "3.9"
   
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty

  web:
    build: .
    command: python3 main.py
    restart: always
    environment:
      - DB_URL=postgresql+asyncpg://postgres:qwerty@db:5432/postgres
      - DB_SYNC_URL=postgresql://postgres:qwerty@db:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - db